### ISSUE TITLE
How to achieve the same css as your image in read me :)

### ISSUE THREAD

**Issue by goxr3plus** [bluebill1049/react-flip-numbers#17]
First of all thank you for the amazing library i am using it on my new stocks website and the effects look pretty lit.

![2020-10-21_23-59-44](https://user-images.githubusercontent.com/20374208/96786907-95721c00-13f9-11eb-8cc6-4ebe9b787845.gif)

Although i can't find out how to achieve the same styling as shown on your read me :) 

![react-flip-numbers](https://user-images.githubusercontent.com/20374208/96786568-2ac0e080-13f9-11eb-8125-d6fc55ee7ded.gif)

**Comment by bluebill1049** [comment]
mostly just styling mate. make sure you pick the right font.

**Comment by goxr3plus** [comment]
lol i mean can't you just provide me how you did it... you just close the ticket omg

**Comment by bluebill1049** [comment]
> lol i mean can't you just provide me how you did it... you just close the ticket omg

lol, you reported as an issue, and it's not an issue to this library. I am not hosting a tutorial in here, instead of giving away code for FREE. If i have "time", i am happy to write a tutorial, but i am still responding to you, i could easily ignoring you. be appreciative for what's here for "FREE". :)

**Comment by goxr3plus** [comment]
I could create only issue or feature request. If that's hard for you... :'( okay

I am digging the library right now there is no documentation and examples like other libraries.

Yes you could ignore me lol, come on i have 100 repos and i help the users of the libraries even giving code solutions.

Anyway... :)

**Comment by bluebill1049** [comment]
> I could create only issue or feature request. If that's hard for you... :'( okay
> 
> I am digging the library right now there is no documentation and examples like other libraries.
> 
> Yes you could ignore me lol, come on i have 100 repos and i help the users of the libraries even giving code solutions.
> 
> Anyway... :)

no, hard feeling. I am only stating the fact above :) 

1. there are documentation for this little tiny lib.
<img width="892" alt="Screen Shot 2020-10-22 at 10 08 18 am" src="https://user-images.githubusercontent.com/10513364/96799292-8a95a680-144e-11eb-9b2f-b2b3eff7cf29.png">

2. you can send PR as well to improve the doc

3. styling problem is not related to this library, if you asking me why this is not working, i will fix and so on, because i give and maintain this library for free and for everyone.

4. i did reply back to you what's the problem that you are having, i could just close it because it's not the issue with the library.

anyway, i am pretty sure you are a nice dude, but you took my reply in the wrong way and at least you think "issue" different as i do.
